# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from autogen import virtual_account_pb2 as autogen_dot_virtual__account__pb2


class VirtualAccountStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateVa = channel.unary_unary(
        '/VirtualAccount/CreateVa',
        request_serializer=autogen_dot_virtual__account__pb2.CreateVaRequest.SerializeToString,
        response_deserializer=autogen_dot_virtual__account__pb2.CreateVaResponse.FromString,
        )
    self.InquiryVa = channel.unary_unary(
        '/VirtualAccount/InquiryVa',
        request_serializer=autogen_dot_virtual__account__pb2.InquiryVaRequest.SerializeToString,
        response_deserializer=autogen_dot_virtual__account__pb2.InquiryVaResponse.FromString,
        )
    self.UpdateVa = channel.unary_unary(
        '/VirtualAccount/UpdateVa',
        request_serializer=autogen_dot_virtual__account__pb2.UpdateVaRequest.SerializeToString,
        response_deserializer=autogen_dot_virtual__account__pb2.UpdateVaResponse.FromString,
        )
    self.DisableVa = channel.unary_unary(
        '/VirtualAccount/DisableVa',
        request_serializer=autogen_dot_virtual__account__pb2.DisableVaRequest.SerializeToString,
        response_deserializer=autogen_dot_virtual__account__pb2.DisableVaResponse.FromString,
        )


class VirtualAccountServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateVa(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InquiryVa(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateVa(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DisableVa(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VirtualAccountServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateVa': grpc.unary_unary_rpc_method_handler(
          servicer.CreateVa,
          request_deserializer=autogen_dot_virtual__account__pb2.CreateVaRequest.FromString,
          response_serializer=autogen_dot_virtual__account__pb2.CreateVaResponse.SerializeToString,
      ),
      'InquiryVa': grpc.unary_unary_rpc_method_handler(
          servicer.InquiryVa,
          request_deserializer=autogen_dot_virtual__account__pb2.InquiryVaRequest.FromString,
          response_serializer=autogen_dot_virtual__account__pb2.InquiryVaResponse.SerializeToString,
      ),
      'UpdateVa': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateVa,
          request_deserializer=autogen_dot_virtual__account__pb2.UpdateVaRequest.FromString,
          response_serializer=autogen_dot_virtual__account__pb2.UpdateVaResponse.SerializeToString,
      ),
      'DisableVa': grpc.unary_unary_rpc_method_handler(
          servicer.DisableVa,
          request_deserializer=autogen_dot_virtual__account__pb2.DisableVaRequest.FromString,
          response_serializer=autogen_dot_virtual__account__pb2.DisableVaResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'VirtualAccount', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
