# Docker Compose Production Environments 
version : '3'
services:
        va-grpc:
                build:
                  context: .
                  dockerfile: dockerfiles/grpc/Dockerfile
                image: bni-va-grpc
                env_file: .env
                entrypoint: python manage.py
                restart: unless-stopped
                networks:
                - va-net
                - lending-engine-net

        mongo:
                image: mongo:latest
                restart: unless-stopped
                networks:
                - va-net
                volumes:
                - "db_volume:/data/db"
networks:
  va-net:
  lending-engine-net:
    external: true

volumes:
  db_volume:
