# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from autogen import transfer_pb2 as autogen_dot_transfer__pb2


class OpgTransferStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TransferInquiry = channel.unary_unary(
        '/OpgTransfer/TransferInquiry',
        request_serializer=autogen_dot_transfer__pb2.TransferInquiryRequest.SerializeToString,
        response_deserializer=autogen_dot_transfer__pb2.TransferInquiryResponse.FromString,
        )
    self.Transfer = channel.unary_unary(
        '/OpgTransfer/Transfer',
        request_serializer=autogen_dot_transfer__pb2.TransferRequest.SerializeToString,
        response_deserializer=autogen_dot_transfer__pb2.TransferResponse.FromString,
        )


class OpgTransferServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TransferInquiry(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Transfer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OpgTransferServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TransferInquiry': grpc.unary_unary_rpc_method_handler(
          servicer.TransferInquiry,
          request_deserializer=autogen_dot_transfer__pb2.TransferInquiryRequest.FromString,
          response_serializer=autogen_dot_transfer__pb2.TransferInquiryResponse.SerializeToString,
      ),
      'Transfer': grpc.unary_unary_rpc_method_handler(
          servicer.Transfer,
          request_deserializer=autogen_dot_transfer__pb2.TransferRequest.FromString,
          response_serializer=autogen_dot_transfer__pb2.TransferResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'OpgTransfer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
