# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from task.investor.rpc.email import email_pb2 as autogen_dot_email__pb2


class EmailNotificationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendEmail = channel.unary_unary(
        '/EmailNotification/SendEmail',
        request_serializer=autogen_dot_email__pb2.SendEmailRequest.SerializeToString,
        response_deserializer=autogen_dot_email__pb2.SendEmailResponse.FromString,
        )


class EmailNotificationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendEmail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EmailNotificationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendEmail': grpc.unary_unary_rpc_method_handler(
          servicer.SendEmail,
          request_deserializer=autogen_dot_email__pb2.SendEmailRequest.FromString,
          response_serializer=autogen_dot_email__pb2.SendEmailResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'EmailNotification', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
