# Docker Compose Production Environments 
version : '3'
services:
        transaction-flask:
                build:
                  context: .
                  dockerfile: dockerfiles/flask/Dockerfile
                image: transaction-engine-services
                env_file: .env
                entrypoint: make run
                restart: unless-stopped
                ports:
                - 12000:5000
                networks:
                - transaction-net
                - lending-engine-net
                - mongo-replicaset-net
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"

        transaction-worker:
                image: transaction-engine-services
                env_file: .env
                entrypoint: make transaction-worker
                restart: unless-stopped
                networks:
                - transaction-net
                - mongo-replicaset-net
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"

        transaction-utils-worker:
                image: transaction-engine-services
                env_file: .env
                entrypoint: make utility-worker
                restart: unless-stopped
                networks:
                - transaction-net
                - lending-engine-net
                - mongo-replicaset-net
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"

        external-worker:
                image: transaction-engine-services
                env_file: .env
                entrypoint: make external-worker
                restart: unless-stopped
                networks:
                - transaction-net
                - lending-engine-net
                - mongo-replicaset-net
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"

        trx-rabbitmq:
                env_file: .env
                image: rabbitmq:3-management
                restart: unless-stopped
                networks:
                - transaction-net

        opg-grpc:
                image: bni-opg-grpc
                env_file: .env
                entrypoint: python manage.py run
                restart: unless-stopped
                networks:
                - transaction-net
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"

networks:
  transaction-net:
  lending-engine-net:
    external: true
  mongo-replicaset-net:
    external: true
