# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autogen/mobile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='autogen/mobile.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x61utogen/mobile.proto\"n\n\x1bSendPushNotificationRequest\x12\x14\n\x0c\x64\x65vice_token\x18\x01 \x01(\t\x12\x12\n\nnotif_type\x18\x02 \x01(\t\x12\x14\n\x0cproduct_type\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\".\n\x1cSendPushNotificationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2k\n\x12MobileNotification\x12U\n\x14SendPushNotification\x12\x1c.SendPushNotificationRequest\x1a\x1d.SendPushNotificationResponse\"\x00\x62\x06proto3')
)




_SENDPUSHNOTIFICATIONREQUEST = _descriptor.Descriptor(
  name='SendPushNotificationRequest',
  full_name='SendPushNotificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_token', full_name='SendPushNotificationRequest.device_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notif_type', full_name='SendPushNotificationRequest.notif_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_type', full_name='SendPushNotificationRequest.product_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='SendPushNotificationRequest.content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=134,
)


_SENDPUSHNOTIFICATIONRESPONSE = _descriptor.Descriptor(
  name='SendPushNotificationResponse',
  full_name='SendPushNotificationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SendPushNotificationResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=182,
)

DESCRIPTOR.message_types_by_name['SendPushNotificationRequest'] = _SENDPUSHNOTIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['SendPushNotificationResponse'] = _SENDPUSHNOTIFICATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendPushNotificationRequest = _reflection.GeneratedProtocolMessageType('SendPushNotificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDPUSHNOTIFICATIONREQUEST,
  '__module__' : 'autogen.mobile_pb2'
  # @@protoc_insertion_point(class_scope:SendPushNotificationRequest)
  })
_sym_db.RegisterMessage(SendPushNotificationRequest)

SendPushNotificationResponse = _reflection.GeneratedProtocolMessageType('SendPushNotificationResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDPUSHNOTIFICATIONRESPONSE,
  '__module__' : 'autogen.mobile_pb2'
  # @@protoc_insertion_point(class_scope:SendPushNotificationResponse)
  })
_sym_db.RegisterMessage(SendPushNotificationResponse)



_MOBILENOTIFICATION = _descriptor.ServiceDescriptor(
  name='MobileNotification',
  full_name='MobileNotification',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=184,
  serialized_end=291,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendPushNotification',
    full_name='MobileNotification.SendPushNotification',
    index=0,
    containing_service=None,
    input_type=_SENDPUSHNOTIFICATIONREQUEST,
    output_type=_SENDPUSHNOTIFICATIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOBILENOTIFICATION)

DESCRIPTOR.services_by_name['MobileNotification'] = _MOBILENOTIFICATION

# @@protoc_insertion_point(module_scope)
