# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from autogen import mobile_pb2 as autogen_dot_mobile__pb2


class MobileNotificationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendPushNotification = channel.unary_unary(
        '/MobileNotification/SendPushNotification',
        request_serializer=autogen_dot_mobile__pb2.SendPushNotificationRequest.SerializeToString,
        response_deserializer=autogen_dot_mobile__pb2.SendPushNotificationResponse.FromString,
        )


class MobileNotificationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendPushNotification(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MobileNotificationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendPushNotification': grpc.unary_unary_rpc_method_handler(
          servicer.SendPushNotification,
          request_deserializer=autogen_dot_mobile__pb2.SendPushNotificationRequest.FromString,
          response_serializer=autogen_dot_mobile__pb2.SendPushNotificationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MobileNotification', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
